# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: 
- main

pool: 
   vmImage: ubuntu-20.04

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: Defensy-env
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:   
          steps:
          - script:
              npm install
              npm run build
              ng build --prod
            displayName: 'npm install and build'
